export const ACCEPTED_PRIVACY_POLICY_KEY = "ACCEPTED_PRIVACY_POLICY_KEY";
export const EMAIL_KEY = "EMAIL_KEY";
export const TOKEN_KEY = "TOKEN_KEY";

export const DONATION_MODAL_SEEN_AT_KEY = "DONATION_MODAL_SEEN_AT_KEY";
export const HAS_AN_AVAILABLE_VOUCHER = "HAS_AN_AVAILABLE_VOUCHER";
export const COMES_FROM_TREASURE = "COMES_FROM_TREASURE";
export const SUBGRAPH_URL = "SUBGRAPH_URL";
export const CHAIN_ID = "CHAIN_ID";
