name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Run lint
        run: |
          yarn lint
      - name: Run tests
        run: |
          yarn test
      - name: Build
        run: |
          yarn build
      - name: Publish package on NPM 📦
        run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
